// scripts/create-table.js
// Creates the Recipes DynamoDB table. This is an alternative to clicking through
// the console (AWS-SETUP-GUIDE.md, Step 2). Run once:  npm run create-table
//
// Requires AWS credentials with permission to create tables (your own admin user
// when running locally). Reads region/table name from env, same as the app.

const {
  CreateTableCommand,
  DescribeTableCommand,
} = require("@aws-sdk/client-dynamodb");
const { client, TABLE_NAME, REGION } = require("../src/config/dynamo");

async function main() {
  console.log(`Region: ${REGION}`);
  console.log(`Creating table: ${TABLE_NAME}`);

  try {
    await client.send(
      new CreateTableCommand({
        TableName: TABLE_NAME,
        // Single partition key. recipeId is a UUID generated by the API.
        AttributeDefinitions: [
          { AttributeName: "recipeId", AttributeType: "S" },
        ],
        KeySchema: [{ AttributeName: "recipeId", KeyType: "HASH" }],
        BillingMode: "PAY_PER_REQUEST", // no capacity planning; good for a project
      })
    );
    console.log("CreateTable request sent. Waiting for ACTIVE status...");

    // Poll until the table is ready.
    for (let i = 0; i < 30; i++) {
      const { Table } = await client.send(
        new DescribeTableCommand({ TableName: TABLE_NAME })
      );
      if (Table.TableStatus === "ACTIVE") {
        console.log("Table is ACTIVE. Done.");
        return;
      }
      await new Promise((r) => setTimeout(r, 2000));
    }
    console.log("Table created but still not ACTIVE after 60s; check the console.");
  } catch (err) {
    if (err.name === "ResourceInUseException") {
      console.log("Table already exists. Nothing to do.");
      return;
    }
    throw err;
  }
}

main().catch((err) => {
  console.error("Failed to create table:", err);
  process.exit(1);
});
